---
id: Idna
name: Idna
full: IDNA normalization library
description: >-
  A library that wraps various backends providing IDNA (Internationalized Domain
  Names in Applications) support.
list: dev
type: library
authors:
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 2.0.0alpha4
  api: 2.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^7
    composer:
      horde/exception: ^3
      horde/util: ^3
  optional:
    ext:
      intl: '*'
